---
- hosts: all
  vars_files:
    - default.config.yml
  vars_prompt:
    - name: restic_password
      prompt: Please enter master password (restic)
      private: true
  roles:
    - firefox
    - restic
    - rdiff
    - copy
