---
- name: "{{ repo }}: Check src {{ src }}"
  stat:
    path: "{{ src }}"
  register: src_result
  failed_when: not (src_result.stat.exists and src_result.stat.isdir is defined and src_result.stat.isdir)

- name: "{{ repo }}: Check repo base folder {{ repo_base }}"
  stat:
    path: "{{ repo_base }}"
  register: repo_base_result

- block:
    - name: "{{ repo }}: Check repo folder {{ repo }}"
      stat:
        path: "{{ repo }}"
      register: repo_result

    - name: "{{ repo }}: Compare"
      shell: rdiff-backup {{ rdiff_excludes_params }} --compare {{ src }} {{ repo }}
      register: compare_result
      changed_when: False
      failed_when: False
      when: repo_result.stat.exists

    - name: "{{ repo }}: Diff"
      debug:
        msg: "{{ compare_result.stdout_lines | default('') }}"
      when: compare_result.stdout_lines is defined

    - name: "{{ repo }}: Backup"
      shell: rdiff-backup {{ rdiff_excludes_params }} {{ src }} {{ repo }}
      register: backup_result
      failed_when: backup_result.rc != 0
      when: not (compare_result.stdout_lines is defined and compare_result.stdout_lines is search('No changes found'))

    - name: "{{ repo }}: Verify"
      shell: rdiff-backup --verify {{ repo }}
      register: verify_result
      changed_when: verify_result.rc != 0
      failed_when: verify_result.rc != 0
      when: backup_result.rc is defined and backup_result.rc == 0
  when: repo_base_result.stat.exists or (not repo_base_result.stat.exists and not skip_backup_if_repo_missing)