---
- name: "Append excludes list"
  set_fact:
    rdiff_excludes_params_list: "{{ rdiff_excludes_params_list | default([]) + [' '.join(('--exclude', item))] }}"
  loop: "{{ rdiff_excludes_default | default([]) }}"

- name: "Set excludes parameter"
  set_fact:
    rdiff_excludes_params: "{{ rdiff_excludes_params_list | default([]) | join(' ') }}"

- name: "Show excludes parameter"
  debug:
    msg: "{{ rdiff_excludes_params }}"

- include_tasks: rdiff_backup.yml
  vars:
    repo: "{{ item.repo }}"
    repo_base: "{{ item.repo | dirname }}"
    src: "{{ item.src }}"
  with_items:
    "{{ rdiff_backups | default([]) }}"
  when: (item.repo is defined) and (item.src is defined)
