---
- include_tasks: local_backup.yml
  vars:
    repo: "{{ item.repo }}"
    repo_base: "{{ item.repo | dirname }}"
    src: "{{ item.src }}"
  with_items:
    "{{ rdiff_backups['local_backups'] | default([]) }}"
  when: (item.repo is defined) and (item.src is defined)
