---
- name: "{{ repo }}: Check src {{ src }}"
  stat:
    path: "{{ src }}"
  register: src_result

- name: "{{ repo }}: Check repo base folder"
  stat:
    path: "{{ repo | dirname }}"
  register: repo_base_result

- block:
    - name: "{{ repo }}: Check repo folder {{ repo }}"
      stat:
        path: "{{ repo }}"
      register: repo_result

    - name: "{{ repo }}: Compare"
      shell: rdiff-backup {{ rdiff_excludes_params }} --compare {{ src }} {{ repo }}
      register: compare_result
      changed_when: false
      failed_when: false
      when: repo_result.stat.exists

    - name: "{{ repo }}: Diff"
      debug:
        msg: "{{ compare_result.stdout_lines | default('') }}"

    - name: "{{ repo }}: Confirm"
      pause:
        prompt: "Proceed with backup? (Y/n)"
      register: rdiff_confirm
      when:
        - not (compare_result.stdout_lines is defined and compare_result.stdout_lines is search('No changes found'))
        - interactive_mode

    - name: "{{ repo }}: Backup"
      shell: rdiff-backup {{ rdiff_excludes_params }} {{ src }} {{ repo }}
      register: backup_result
      when:
        - not (compare_result.stdout_lines is defined and compare_result.stdout_lines is search('No changes found'))
        - not interactive_mode or (interactive_mode and rdiff_confirm.user_input | lower == 'y')

    - name: "{{ repo }}: Check repo data"
      shell: rdiff-backup --verify {{ repo }}
      when: backup_result.rc is defined and backup_result.rc == 0
      tags:
        - check
  when:
    - repo_base_result.stat.exists
    - src_result.stat.exists
    - src_result.stat.isdir is defined and src_result.stat.isdir
