---
- include_tasks: local_backup.yml
  vars:
    repo: "{{ item.repo }}"
    src: "{{ item.src }}"
    password: "{{ item.password }}"
  with_items:
    "{{ restic_backups['local_backups'] | default([]) }}"
