---
- name: "Prompt restic master password"
  pause:
    prompt: "Enter restic repo password: (Exit restic backups with empty input)"
    echo: no
  register: restic_prompt
  when: restic_password is not defined

- name: "Set restic master password"
  set_fact:
    restic_password: "{{ restic_prompt.user_input }}"
  when: restic_password is not defined

- block:
  - name: "Set excludes parameter"
    set_fact:
      restic_excludes_params: "{{ ['--exclude='] | product(restic_excludes_default) | map('join') | list | join(' ') }}"

  - include_tasks: restic_backup.yml
    vars:
      repo: "{{ item.repo }}"
      repo_base: "{{ item.repo | dirname }}"
      src: "{{ item.src }}"
    with_items:
      "{{ restic_backups | default([]) }}"
    when:
      - (item.repo is defined) and (item.src is defined)
      - restic_password != ''
  tags:
    - backup

- include_tasks: restic_check.yml
  vars:
    repo: "{{ item.repo }}"
  with_items:
    "{{ restic_backups | default([]) }}"
  when:
    - (item.repo is defined) and (item.src is defined)
    - restic_password != ''
  tags:
    - check
