---
- name: "repo {{ repo }}: Check repo stats"
  stat:
    path: "{{ repo }}"
  register: repo_result
  tags:
    - check

- name: "repo {{ repo }}: Check repo data"
  shell: restic check --read-data
  environment:
    RESTIC_REPOSITORY: "{{ repo }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
  when: repo_result.stat.exists
  tags:
    - check
