---
- name: "Copy: Check dest folder {{ dest }}"
  stat:
    path: "{{ dest }}"
  register: dest_result

- name: "Copy: {{ src }} to {{ dest }}"
  copy:
    src: "{{ src }}"
    dest: "{{ dest }}"
  when: dest_result.stat.exists
