---
- block:
  - include_tasks: copy.yml
    vars:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      "{{ copy_backups | default([]) }}"
    when: (item.src is defined) and (item.dest is defined)
  tags:
    - backup
